name: No Response

on:
  workflow_dispatch:
  issue_comment:
    types: [created]
  schedule:
    - cron: '5 1 * * *'

jobs:
  noResponse:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v8
        with:
          debug-only: true
          days-before-issue-stale: 7
          days-before-issue-close: 3
          only-labels: "waiting-for-response"
          labels-to-remove-when-unstale: "waiting-for-response"
          stale-issue-message: "This issue will be closed soon because there has been no response."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
