name: Update from Template

on:
  schedule:
    - cron: '55 2 * * 1'
  workflow_dispatch:

env:
  UPDATE_BRANCH: update-from-template
  REMOTE_URL: https://github.com/xdev-software/vaadin-addon-template.git
  REMOTE_BRANCH: master

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Init Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Main workflow
        id: main
        run: |
          echo "Adding remote template-repo"
          git remote add template ${{ env.REMOTE_URL }}
          
          echo "Fetching remote template repo"
          git fetch template
          
          echo "Deleting local branch that will contain the updates - if present"
          git branch -D ${{ env.UPDATE_BRANCH }} || true
          
          echo "Checking if the remote template repo has new commits"
          git rev-list ..template/${{ env.REMOTE_BRANCH }}

          if [ $(git rev-list --count ..template/${{ env.REMOTE_BRANCH }}) -eq 0 ]; then
            echo "There are no commits new commits on the template repo"
            
            echo "Deleting origin branch that contains the updates - if present"
            git push -f origin --delete ${{ env.UPDATE_BRANCH }} || true
            
            echo "::set-output name=abort::1"
            exit 0
          fi
          
          echo "Found new commits on the template repo"
          
          echo "Creating update branch"
          git branch ${{ env.UPDATE_BRANCH }} template/${{ env.REMOTE_BRANCH }}
          git branch --unset-upstream ${{ env.UPDATE_BRANCH }}
          
          echo "Pushing update branch"
          git push -f -u origin ${{ env.UPDATE_BRANCH }}
          
          echo "Getting current branch"
          currentbranch=$(git branch --show-current)
          echo "Current branch is $currentbranch"
          echo "::set-output name=currentbranch::$currentbranch"

          echo "::set-output name=abort::0"
          
      - name: pull-request
        uses: repo-sync/pull-request@v2
        if: steps.main.outputs.abort == 0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ env.UPDATE_BRANCH }}
          destination_branch: ${{ steps.main.outputs.currentbranch }}
          pr_title: "Sync from template"
          pr_body: "An automated PR to sync changes from the template into this repo"
          
